spring.application.name=tg
spring.datasource.url=jdbc:postgresql://db-travelguide.cyl0icyk0qzd.us-east-1.rds.amazonaws.com:5432/dbprod
spring.datasource.username=postgres
spring.datasource.password=travelguide
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
